import Head from 'next/head'
import Image from 'next/image'
import Particles from '../components/Particles'

export default function Home() {
  return (
    <div style={{backgroundColor: 'black'}}>
      <Head>
        <title>Jack Youkstetter Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh'}}>
        <h1 style={{color: 'white'}}>Hey</h1>
        
      </div>
      <Particles/>
    </div>
  )
}
